[2024-04-26T09:01:58.093] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:01:58.093] [ERROR] attendance - Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1",
  sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outcome, a.sessiontime AS SessionTime FROM Users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = :userID;'
}
[2024-04-26T09:01:58.094] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:01:58.094] [ERROR] attendance - {
  status: 'failed',
  err: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1",
    sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outcome, a.sessiontime AS SessionTime FROM Users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = :userID;'
  },
  data: { bResult: false }
}
[2024-04-26T09:02:28.605] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:02:28.605] [ERROR] attendance - Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1",
  sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outcome, a.sessiontime AS SessionTime FROM Users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = :userID;'
}
[2024-04-26T09:02:28.605] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:02:28.605] [ERROR] attendance - {
  status: 'failed',
  err: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userID' at line 1",
    sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outcome, a.sessiontime AS SessionTime FROM Users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = :userID;'
  },
  data: { bResult: false }
}
[2024-04-26T09:04:16.669] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:04:16.669] [ERROR] attendance - Error: Table 'u383951428_Mayur_Motors.Users' doesn't exist
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'u383951428_Mayur_Motors.Users' doesn't exist",
  sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM Users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
}
[2024-04-26T09:04:16.671] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:04:16.671] [ERROR] attendance - {
  status: 'failed',
  err: Error: Table 'u383951428_Mayur_Motors.Users' doesn't exist
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'u383951428_Mayur_Motors.Users' doesn't exist",
    sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM Users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
  },
  data: { bResult: false }
}
[2024-04-26T09:04:34.214] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:04:34.215] [ERROR] attendance - Error: Table 'u383951428_Mayur_Motors.User_profile' doesn't exist
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'u383951428_Mayur_Motors.User_profile' doesn't exist",
  sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
}
[2024-04-26T09:04:34.216] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:04:34.216] [ERROR] attendance - {
  status: 'failed',
  err: Error: Table 'u383951428_Mayur_Motors.User_profile' doesn't exist
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'u383951428_Mayur_Motors.User_profile' doesn't exist",
    sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN Enrollments e ON up.ID = e.User_profile_ID INNER JOIN Attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
  },
  data: { bResult: false }
}
[2024-04-26T09:05:16.786] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:05:16.786] [ERROR] attendance - Error: Table 'u383951428_Mayur_Motors.User_profile' doesn't exist
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'u383951428_Mayur_Motors.User_profile' doesn't exist",
  sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN enrollments e ON up.ID = e.User_profile_ID INNER JOIN attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
}
[2024-04-26T09:05:16.788] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:05:16.788] [ERROR] attendance - {
  status: 'failed',
  err: Error: Table 'u383951428_Mayur_Motors.User_profile' doesn't exist
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'u383951428_Mayur_Motors.User_profile' doesn't exist",
    sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM users u INNER JOIN User_profile up ON u.ID = up.UserId INNER JOIN enrollments e ON up.ID = e.User_profile_ID INNER JOIN attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
  },
  data: { bResult: false }
}
[2024-04-26T09:05:31.942] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:05:31.942] [ERROR] attendance - Error: Column 'userID' in where clause is ambiguous
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_NON_UNIQ_ERROR',
  errno: 1052,
  sqlState: '23000',
  sqlMessage: "Column 'userID' in where clause is ambiguous",
  sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM users u INNER JOIN user_profile up ON u.ID = up.UserId INNER JOIN enrollments e ON up.ID = e.User_profile_ID INNER JOIN attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
}
[2024-04-26T09:05:31.944] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:05:31.944] [ERROR] attendance - {
  status: 'failed',
  err: Error: Column 'userID' in where clause is ambiguous
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NON_UNIQ_ERROR',
    errno: 1052,
    sqlState: '23000',
    sqlMessage: "Column 'userID' in where clause is ambiguous",
    sql: 'SELECT up.ID AS userprofileId, up.DisplayName, up.isActive, e.ID AS enrollmentId, e.Type, e.SubType, a.inTime, a.outTime, a.session FROM users u INNER JOIN user_profile up ON u.ID = up.UserId INNER JOIN enrollments e ON up.ID = e.User_profile_ID INNER JOIN attendance a ON up.ID = a.User_profile_ID WHERE u.ID = userID;'
  },
  data: { bResult: false }
}
[2024-04-26T09:33:40.563] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:33:40.563] [ERROR] attendance - Error: Unknown column 'UserProfileId' in 'where clause'
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'UserProfileId' in 'where clause'",
  sql: 'SELECT * FROM `attendance` WHERE `UserProfileId` = NULL;'
}
[2024-04-26T09:33:40.564] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:33:40.564] [ERROR] attendance - {
  status: 'failed',
  err: Error: Unknown column 'UserProfileId' in 'where clause'
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'UserProfileId' in 'where clause'",
    sql: 'SELECT * FROM `attendance` WHERE `UserProfileId` = NULL;'
  },
  data: { bResult: false }
}
[2024-04-26T09:33:55.805] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error in fetching attendance
[2024-04-26T09:33:55.805] [ERROR] attendance - Error: Unknown column 'UserProfile_Id' in 'where clause'
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'UserProfile_Id' in 'where clause'",
  sql: 'SELECT * FROM `attendance` WHERE `UserProfile_Id` = NULL;'
}
[2024-04-26T09:33:55.807] [TRACE] attendance - customer-attendance-fetchAttendance - undefined - error thrown
[2024-04-26T09:33:55.807] [ERROR] attendance - {
  status: 'failed',
  err: Error: Unknown column 'UserProfile_Id' in 'where clause'
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'UserProfile_Id' in 'where clause'",
    sql: 'SELECT * FROM `attendance` WHERE `UserProfile_Id` = NULL;'
  },
  data: { bResult: false }
}
