[2024-05-11T04:23:09.968] [TRACE] attendance - customer-attendance-addAttendance - undefined - error in inserting attendance
[2024-05-11T04:23:09.969] [ERROR] attendance - Error: Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_NO_REFERENCED_ROW_2',
  errno: 1452,
  sqlState: '23000',
  sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
  sql: "INSERT INTO `attendance` (`Enrollment_ID`, `Type`, `isPresent`, `inTime`, `outTime`, `session`, `Vehicle_ID`) VALUES ('30','HGV','false','2024-05-11 09:53:00.000','2024-05-11 12:53:00.000','180.0','null');"
}
[2024-05-11T04:23:09.972] [TRACE] attendance - customer-attendance-addAttendance - 30 - error thrown
[2024-05-11T04:23:09.972] [ERROR] attendance - {
  status: 'failed',
  err: Error: Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
    sql: "INSERT INTO `attendance` (`Enrollment_ID`, `Type`, `isPresent`, `inTime`, `outTime`, `session`, `Vehicle_ID`) VALUES ('30','HGV','false','2024-05-11 09:53:00.000','2024-05-11 12:53:00.000','180.0','null');"
  },
  data: { bResult: false }
}
[2024-05-11T04:23:15.833] [TRACE] attendance - customer-attendance-addAttendance - undefined - error in inserting attendance
[2024-05-11T04:23:15.833] [ERROR] attendance - Error: Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_NO_REFERENCED_ROW_2',
  errno: 1452,
  sqlState: '23000',
  sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
  sql: "INSERT INTO `attendance` (`Enrollment_ID`, `Type`, `isPresent`, `inTime`, `outTime`, `session`, `Vehicle_ID`) VALUES ('30','HGV','false','2024-05-11 09:53:00.000','2024-05-11 12:53:00.000','180.0','null');"
}
[2024-05-11T04:23:15.833] [TRACE] attendance - customer-attendance-addAttendance - 30 - error thrown
[2024-05-11T04:23:15.833] [ERROR] attendance - {
  status: 'failed',
  err: Error: Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
    sql: "INSERT INTO `attendance` (`Enrollment_ID`, `Type`, `isPresent`, `inTime`, `outTime`, `session`, `Vehicle_ID`) VALUES ('30','HGV','false','2024-05-11 09:53:00.000','2024-05-11 12:53:00.000','180.0','null');"
  },
  data: { bResult: false }
}
[2024-05-11T04:23:21.075] [TRACE] attendance - customer-attendance-addAttendance - undefined - error in inserting attendance
[2024-05-11T04:23:21.075] [ERROR] attendance - Error: Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_NO_REFERENCED_ROW_2',
  errno: 1452,
  sqlState: '23000',
  sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
  sql: "INSERT INTO `attendance` (`Enrollment_ID`, `Type`, `isPresent`, `inTime`, `outTime`, `session`, `Vehicle_ID`) VALUES ('30','HGV','false','2024-05-11 09:53:00.000','2024-05-11 12:53:00.000','180.0','null');"
}
[2024-05-11T04:23:21.075] [TRACE] attendance - customer-attendance-addAttendance - 30 - error thrown
[2024-05-11T04:23:21.075] [ERROR] attendance - {
  status: 'failed',
  err: Error: Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
      at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`u383951428_Mayur_Motors`.`attendance`, CONSTRAINT `fk_vehicle_for_attendance` FOREIGN KEY (`Vehicle_ID`) REFERENCES `vehicles` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
    sql: "INSERT INTO `attendance` (`Enrollment_ID`, `Type`, `isPresent`, `inTime`, `outTime`, `session`, `Vehicle_ID`) VALUES ('30','HGV','false','2024-05-11 09:53:00.000','2024-05-11 12:53:00.000','180.0','null');"
  },
  data: { bResult: false }
}
[2024-05-11T04:32:12.328] [TRACE] attendance - customer-attendance-fetchalluserAttendance - 9 - error in fetching enrollment
[2024-05-11T04:32:12.328] [ERROR] attendance - Error: Table 'u383951428_Mayur_Motors.enrollment' doesn't exist
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'u383951428_Mayur_Motors.enrollment' doesn't exist",
  sql: "SELECT enrollment.*, user_profile.displayName FROM enrollment JOIN user_profile ON enrollment.User_profile_Id = user_profile.ID JOIN user ON user_profile.user_id = user.id WHERE user.id = '9';"
}
[2024-05-11T04:32:30.740] [TRACE] attendance - customer-attendance-fetchalluserAttendance - 9 - error in fetching enrollment
[2024-05-11T04:32:30.740] [ERROR] attendance - Error: Table 'u383951428_Mayur_Motors.user' doesn't exist
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'u383951428_Mayur_Motors.user' doesn't exist",
  sql: "SELECT enrollments.*, user_profile.displayName FROM enrollments JOIN user_profile ON enrollments.User_profile_Id = user_profile.ID JOIN user ON user_profile.user_id = user.id WHERE user.id = '9';"
}
[2024-05-11T04:36:09.453] [TRACE] attendance - customer-attendance-fetchalluserAttendance - 9 - error in fetching enrollment
[2024-05-11T04:36:09.453] [ERROR] attendance - Error: Unknown column 'user.id' in 'where clause'
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'user.id' in 'where clause'",
  sql: "SELECT enrollments.*, user_profile.displayName FROM enrollments JOIN user_profile ON enrollments.User_profile_Id = user_profile.ID JOIN users ON user_profile.user_id = users.id WHERE user.id = '9';"
}
[2024-05-11T04:36:27.152] [TRACE] attendance - customer-attendance-fetchalluserAttendance - 9 - error in fetching enrollment
[2024-05-11T04:36:27.152] [ERROR] attendance - Error: Unknown column 'user_profile.user_id' in 'on clause'
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'user_profile.user_id' in 'on clause'",
  sql: "SELECT enrollments.*, user_profile.displayName FROM enrollments JOIN user_profile ON enrollments.User_profile_Id = user_profile.ID JOIN users ON user_profile.user_id = users.id WHERE users.id = '9';"
}
[2024-05-11T04:36:49.259] [TRACE] attendance - customer-attendance-fetchalluserAttendance - 9 - error in fetching enrollment
[2024-05-11T04:36:49.260] [ERROR] attendance - Error: Unknown column 'user_profile.user_id' in 'on clause'
    at Packet.asError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'user_profile.user_id' in 'on clause'",
  sql: "SELECT enrollments.*, user_profile.displayName FROM enrollments JOIN user_profile ON enrollments.User_profile_Id = user_profile.ID JOIN users ON user_profile.user_id = users.id WHERE users.id = '9';"
}
